baseURL = "https://www.appuio.ch/"
languageCode = "en-us"
theme = "appuio"

DefaultContentLanguage = "de"

[params]
  title = "APPUiO - Swiss Container Platform"
  # Shortcodes that must be closed
  # If the shortcode uses .Inner then add it here!
  mustCloseShortcodes = ["section","upcoming-events"]

[module]
  [[module.imports]]
    path = "github.com/jgthms/bulma"
    [[module.imports.mounts]]
    source = "sass"
    target = "assets/scss/bulma"

[languages]
  [languages.en]
    languageName = "English"

  [[languages.en.menu.main]]
    identifier = "offering"
    url = "/"
    name = "Offering"
    weight = 10
  [[languages.en.menu.main]]
    identifier = "community"
    url = "/"
    name = "Community"
    weight = 20
  # Defined here and not in _index.en.md,
  # because NetlifyCMS also lists _index.md files:
  # https://github.com/netlify/netlify-cms/issues/2727
  # This is probably a bug, because we use Bundles.
  [[languages.en.menu.main]]
    url = "/en/blog/"
    name = "Blog"
    parent = "community"
    weight = 1
  [[languages.en.menu.main]]
    url = "/en/events/"
    name = "Events"
    parent = "community"
    weight = 2
  [[languages.en.menu.main]]
    url = "https://community.appuio.ch"
    name = "Community Chat"
    parent = "community"
    weight = 3
  [[languages.en.menu.main]]
    url = "https://docs.appuio.ch"
    name = "Docs"
    parent = "community"
    weight = 4
  [[languages.en.menu.main]]
    identifier = "techlabs"
    url = "/"
    name = "Techlabs"
    weight = 30
  [[languages.en.menu.main]]
    url = "/en/#contact"
    name = "Contact"
    weight = 100

  [languages.de]
    languageName = "Deutsch"

  [[languages.de.menu.main]]
    identifier = "offering"
    url = "/"
    name = "Angebot"
    weight = 10
  [[languages.de.menu.main]]
    identifier = "community"
    url = "/"
    name = "Community"
    weight = 20
  # Defined here and not in _index.en.md,
  # because NetlifyCMS also lists _index.md files:
  # https://github.com/netlify/netlify-cms/issues/2727
  # This is probably a bug, because we use Bundles.
  [[languages.de.menu.main]]
    url = "/blog/"
    name = "Blog"
    parent = "community"
    weight = 1
  [[languages.de.menu.main]]
    url = "/events/"
    name = "Events"
    parent = "community"
    weight = 2
  [[languages.de.menu.main]]
    url = "https://community.appuio.ch"
    name = "Community Chat"
    parent = "community"
    weight = 3
  [[languages.de.menu.main]]
    url = "https://docs.appuio.ch"
    name = "Docs"
    parent = "community"
    weight = 4
  [[languages.de.menu.main]]
    identifier = "techlabs"
    url = "/"
    name = "Techlabs"
    weight = 30

  [[languages.de.menu.main]]
    url = "/#kontakt"
    name = "Kontakt"
    weight = 100

[markup.goldmark.renderer]
  unsafe = true
